CUSTOMER_ACCOUNT_DETAILS
INSERT INTO CUSTOMER_ACCOUNT_DETAILS 
(CUSTOMER_ID, ACCOUNT_NUMBER, BALANCE, TRANSACTION_MODE, TRANSACTION_DATE) VALUES
('456',123,100.00,'D',sysdate); 

INSERT INTO CUSTOMER_ACCOUNT_DETAILS 
(CUSTOMER_ID, ACCOUNT_NUMBER, BALANCE, TRANSACTION_MODE, TRANSACTION_DATE) VALUES
('456',123,100.00,'D',sysdate); 
INSERT INTO CUSTOMER_ACCOUNT_DETAILS 
(CUSTOMER_ID, ACCOUNT_NUMBER, BALANCE, TRANSACTION_MODE, TRANSACTION_DATE) VALUES
('456',123,100.00,'C',sysdate); 

INSERT INTO CUSTOMER_ACCOUNT_DETAILS 
(CUSTOMER_ID, ACCOUNT_NUMBER, BALANCE, TRANSACTION_MODE, TRANSACTION_DATE) VALUES
('456',123,1.00,'D',sysdate); 

INSERT INTO CUSTOMER_ACCOUNT_DETAILS 
(CUSTOMER_ID, ACCOUNT_NUMBER, BALANCE, TRANSACTION_MODE, TRANSACTION_DATE) VALUES
('456',123,2.00,'D',sysdate); 

